### ISSUE TITLE
Feature request: option to not cross filesystem boundaries

### ISSUE THREAD

**Issue by elder-n00b** [salihgerdan/spaceman#4]
An option to not cross filesystem boundaries (e.g. if `/home` is mounted from another filesystem, do not enter it when scanning `/`).

Some other tools use `-x` command line option for this.

**Comment by salihgerdan** [comment]
Hello there. This has been the default behavior since commit 6e03365. Before the change, scanning `/` would be impractical due to the absurd sizes reported by the files in `/proc`.
Conversely, I have not made a switch to turn off this behavior.
In case it bugged out for you I will try to help.
